services:
  mysql:
    image: mysql
    container_name: mysql-acolhemais
    ports:
      - "3306:3306"
    volumes:
      - mysql_acolhemais_data:/var/lib/mysql

  node:
    image: node:22
    container_name: node-acolhemais
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    network_mode: host
    command: >
      sh -c "npm install && npm start"

volumes:
  mysql_acolhemais_data:
