services:
  db:
    image: mysql
    container_name: mysql-acolhemais
    environment:
      MYSQL_ROOT_PASSWORD: AcolheMais@2025
      MYSQL_DATABASE: acolhemais_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_acolhemais_data:/var/lib/mysql

  app:
    image: node:22-alpine
    container_name: acolhemais
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev"]

    volumes:
      - ./:/app
    ports: 
      - 3000:3000
      - 3001:3001 

volumes:
  mysql_acolhemais_data:
