services:
  db:
    image: mysql
    container_name: mysql-acolhemais
    environment:
      MYSQL_ROOT_PASSWORD: AcolheMais@2025
      MYSQL_DATABASE: acolhemais_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_acolhemais_data:/var/lib/mysql

  app:
    build: .
    container_name: acolhemais
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./.env:/app/backend/.env 
    ports: 
      - 3000:3000
      - 3001:3001
    env_file:
      - .env

volumes:
  mysql_acolhemais_data:
